/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.du.sirigaddepriyanka.view;

import edu.du.sirigaddepriyanka.model.business.manager.carshowmanager.CarShowManager;
import edu.du.sirigaddepriyanka.model.business.manager.carshowownermanager.CarShowOwnerManager;
import edu.du.sirigaddepriyanka.model.business.manager.ownermanager.OwnerManager;
import edu.du.sirigaddepriyanka.model.business.manager.vehiclemanager.VehicleManager;
import edu.du.sirigaddepriyanka.model.domain.CarShow;
import edu.du.sirigaddepriyanka.controller.carshowcontroller.CarShowUIController;
import java.awt.Container;
import java.util.ArrayList;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author priyankasirigadde
 */
public class CarShowUI extends javax.swing.JFrame {

    private OwnerManager ownerManager = null;
    private VehicleManager vehicleManager = null;
    private CarShowManager carShowManager = null;
    private CarShowOwnerManager carShowOwnerManager = null;
    private CarShowMainMenu carShowMainMenu = null;

    private final Container container = getContentPane();

    /**
     * Creates new form CarShowUI
     * @param carShowMainMenu
     * @throws java.lang.Exception
     */
    public CarShowUI(CarShowMainMenu carShowMainMenu) throws Exception {
        setTitle("Car Show UI");
        initComponents();

        this.carShowMainMenu = carShowMainMenu;
        ownerManager = carShowMainMenu.getOwnerManager();
        vehicleManager = carShowMainMenu.getVehicleManager();
        carShowManager = carShowMainMenu.getCarShowManager();
        carShowOwnerManager = carShowMainMenu.getCarShowOwnerManager();

        ArrayList<CarShow> carShowArrayList = carShowManager.getArrayList();

        carShowIDComboBox.removeAllItems();
        for (CarShow carShow : carShowArrayList) {
            carShowIDComboBox.addItem(carShow.getCarShowID());
        }
        carShowIDComboBox.setSelectedIndex(0);
        carShowIDComboBox.setEditable(true);

        CarShowUIController carShowUIController = new CarShowUIController(this);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent ev) {

            }
        });
        carShowMainMenu.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carShowIDLabel = new javax.swing.JLabel();
        carShowTitleLabel = new javax.swing.JLabel();
        carShowTitleTextField = new javax.swing.JTextField();
        carShowDateLabel = new javax.swing.JLabel();
        carShowDateTextField = new javax.swing.JTextField();
        isCarShowSanctionedRadioButton = new javax.swing.JRadioButton();
        carShowFindButton = new javax.swing.JButton();
        carShowAddButton = new javax.swing.JButton();
        carShowRemoveButton = new javax.swing.JButton();
        carShowIDComboBox = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        carShowIDLabel.setText("Car Show ID");

        carShowTitleLabel.setText("Car Show Title");

        carShowDateLabel.setText("Car Show Date");

        isCarShowSanctionedRadioButton.setText("is Car Show Sanctioned");

        carShowFindButton.setText("Find");

        carShowAddButton.setText("Add");

        carShowRemoveButton.setText("Remove");

        carShowIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jMenu1.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Exit the System");
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isCarShowSanctionedRadioButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(carShowFindButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                            .addComponent(carShowAddButton)
                            .addGap(54, 54, 54)
                            .addComponent(carShowRemoveButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(carShowIDLabel)
                                .addComponent(carShowTitleLabel)
                                .addComponent(carShowDateLabel))
                            .addGap(64, 64, 64)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(carShowTitleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(carShowDateTextField)
                                .addComponent(carShowIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carShowIDLabel)
                    .addComponent(carShowIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carShowTitleLabel)
                    .addComponent(carShowTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carShowDateLabel)
                    .addComponent(carShowDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(isCarShowSanctionedRadioButton)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carShowFindButton)
                    .addComponent(carShowAddButton)
                    .addComponent(carShowRemoveButton))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarShowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CarShowUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carShowAddButton;
    private javax.swing.JLabel carShowDateLabel;
    private javax.swing.JTextField carShowDateTextField;
    private javax.swing.JButton carShowFindButton;
    private javax.swing.JComboBox<String> carShowIDComboBox;
    private javax.swing.JLabel carShowIDLabel;
    private javax.swing.JButton carShowRemoveButton;
    private javax.swing.JLabel carShowTitleLabel;
    private javax.swing.JTextField carShowTitleTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JRadioButton isCarShowSanctionedRadioButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public OwnerManager getOwnerManager() {
        return ownerManager;
    }

    public VehicleManager getVehicleManager() {
        return vehicleManager;
    }

    public CarShowManager getCarShowManager() {
        return carShowManager;
    }

    public CarShowOwnerManager getCarShowOwnerManager() {
        return carShowOwnerManager;
    }

    public CarShowMainMenu getCarShowMainMenu() {
        return carShowMainMenu;
    }

    public Container getContainer() {
        return container;
    }

    public javax.swing.JButton getCarShowAddButton() {
        return carShowAddButton;
    }

    public javax.swing.JComboBox<String> getCarShowIDComboBox() {
        return carShowIDComboBox;
    }

    public javax.swing.JLabel getCarShowDateLabel() {
        return carShowDateLabel;
    }

    public javax.swing.JTextField getCarShowDateTextField() {
        return carShowDateTextField;
    }

    public javax.swing.JButton getCarShowFindButton() {
        return carShowFindButton;
    }

    public javax.swing.JLabel getCarShowIDLabel() {
        return carShowIDLabel;
    }

    public javax.swing.JButton getCarShowRemoveButton() {
        return carShowRemoveButton;
    }

    public javax.swing.JLabel getCarShowTitleLabel() {
        return carShowTitleLabel;
    }

    public javax.swing.JTextField getCarShowTitleTextField() {
        return carShowTitleTextField;
    }

    public javax.swing.JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public javax.swing.JRadioButton getIsCarShowSanctionedRadioButton() {
        return isCarShowSanctionedRadioButton;
    }

    public javax.swing.JMenu getjMenu1() {
        return jMenu1;
    }

    public javax.swing.JMenu getjMenu2() {
        return jMenu2;
    }

    public javax.swing.JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    /*
    *displays the information
    */
    public void putCarShowInfo(CarShow inCarShow) {
        CarShow carShow = inCarShow;

        carShowIDComboBox.setSelectedItem(carShow.getCarShowID());
        carShowTitleTextField.setText(carShow.getCarShowTitle());
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String strDate = dateFormat.format(carShow.getCarShowDate());
        carShowDateTextField.setText(strDate);
        isCarShowSanctionedRadioButton.setSelected(carShow.isIsSanctioned());
    }

    /*
    *retrieves the information
    */
    public CarShow getCarShowInfo() throws ParseException {
        CarShow carShow = new CarShow();

        carShow.setCarShowID((String) carShowIDComboBox.getSelectedItem());
        carShow.setCarShowTitle(carShowTitleTextField.getText());
        Date date = new SimpleDateFormat("dd/MM/yyyy").parse(carShowDateTextField.getText());
        carShow.setCarShowDate(date);
        carShow.setIsSanctioned(isCarShowSanctionedRadioButton.isSelected());
        return carShow;
    }

    /*
    *clears the frame
    */
    public void clearCarShowInfo() {
        carShowIDComboBox.setSelectedItem(0);
        carShowTitleTextField.setText("");
        carShowDateTextField.setText("");
        isCarShowSanctionedRadioButton.setSelected(false);
    }
}
