/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.du.sirigaddepriyanka.view;

import edu.du.sirigaddepriyanka.controller.CarShowMainMenuController;
import edu.du.sirigaddepriyanka.model.business.manager.carshowmanager.CarShowManager;
import edu.du.sirigaddepriyanka.model.business.manager.carshowownermanager.CarShowOwnerManager;
import edu.du.sirigaddepriyanka.model.business.manager.ownermanager.OwnerManager;
import edu.du.sirigaddepriyanka.model.business.manager.persistmanager.PersistManager;
import edu.du.sirigaddepriyanka.model.business.manager.vehiclemanager.VehicleManager;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author priyankasirigadde
 */
public class CarShowMainMenu extends javax.swing.JFrame {

    private static OwnerManager ownerManager = new OwnerManager();
    private static VehicleManager vehicleManager = new VehicleManager();
    private static CarShowManager carShowManager = new CarShowManager();
    private static CarShowOwnerManager carShowOwnerManager = new CarShowOwnerManager();
    private static PersistManager persistManager = new PersistManager();
    private static final Logger LOGGER = Logger.getLogger(CarShowMainMenu.class.getName());
    private final Container container = getContentPane();

    /**
     * Creates new form CarShowMainMenu
     */
    public CarShowMainMenu() {

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension windowSize = new Dimension((screenSize.width / 2) + 100, (screenSize.height / 2) + 100);
        setPreferredSize(windowSize);
        setLocation(((screenSize.width - windowSize.width) / 2), ((screenSize.height - windowSize.height) / 2));
        setTitle("Car Show Main Menu");
        initComponents();

        ownerMenuItem.setEnabled(false);
        vehicleMenuItem.setEnabled(false);
        carShowMenuItem.setEnabled(false);
        carShowOwnerMenuItem.setEnabled(false);

        try {
            persistManager.loadPersistData(ownerManager, vehicleManager, carShowManager, carShowOwnerManager);
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Exception occurred while loading XML/JSON file :", e);
        }

        CarShowMainMenuController carShowMainMenuController = new CarShowMainMenuController(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userIDLabel = new javax.swing.JLabel();
        userIDTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        carShowMainMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        objectMenuItem = new javax.swing.JMenu();
        ownerMenuItem = new javax.swing.JMenuItem();
        vehicleMenuItem = new javax.swing.JMenuItem();
        carShowMenuItem = new javax.swing.JMenuItem();
        carShowOwnerMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userIDLabel.setText("User ID");

        passwordLabel.setText("Password");

        submitButton.setText("Submit");

        jMenu1.setText("File");
        jMenu1.setToolTipText("Exit the System");

        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Exit the System");
        jMenu1.add(exitMenuItem);

        carShowMainMenu.add(jMenu1);

        jMenu2.setText("Edit");
        carShowMainMenu.add(jMenu2);

        objectMenuItem.setText("Object");

        ownerMenuItem.setText("Owner");
        ownerMenuItem.setToolTipText("Process the Owner");
        objectMenuItem.add(ownerMenuItem);

        vehicleMenuItem.setText("Vehicle");
        vehicleMenuItem.setToolTipText("Process the Vehicle");
        objectMenuItem.add(vehicleMenuItem);

        carShowMenuItem.setText("Car Show");
        carShowMenuItem.setToolTipText("Process the Car Show");
        objectMenuItem.add(carShowMenuItem);

        carShowOwnerMenuItem.setText("Car Show Owner");
        carShowOwnerMenuItem.setToolTipText("Process the Car Show Owner");
        objectMenuItem.add(carShowOwnerMenuItem);

        carShowMainMenu.add(objectMenuItem);

        setJMenuBar(carShowMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel)
                            .addComponent(userIDLabel))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(passwordField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(submitButton)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIDLabel)
                    .addComponent(userIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(submitButton)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *run method for the GUI
     */
    public static void runPortfolioProject() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarShowMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CarShowMainMenu().setVisible(true);
                } catch (Exception e) {
                    LOGGER.log(Level.FINE, "Exception in CarShowMainMenu", e);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar carShowMainMenu;
    private javax.swing.JMenuItem carShowMenuItem;
    private javax.swing.JMenuItem carShowOwnerMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu objectMenuItem;
    private javax.swing.JMenuItem ownerMenuItem;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JTextField userIDTextField;
    private javax.swing.JMenuItem vehicleMenuItem;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JMenuBar getCarShowMainMenu() {
        return carShowMainMenu;
    }

    public javax.swing.JMenuItem getCarShowMenuItem() {
        return carShowMenuItem;
    }

    public javax.swing.JMenuItem getCarShowOwnerMenuItem() {
        return carShowOwnerMenuItem;
    }

    public javax.swing.JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public javax.swing.JMenu getjMenu1() {
        return jMenu1;
    }

    public javax.swing.JMenu getjMenu2() {
        return jMenu2;
    }

    public javax.swing.JMenu getObjectMenuItem() {
        return objectMenuItem;
    }

    public javax.swing.JMenuItem getOwnerMenuItem() {
        return ownerMenuItem;
    }

    public javax.swing.JMenuItem getVehicleMenuItem() {
        return vehicleMenuItem;
    }

    public static OwnerManager getOwnerManager() {
        return ownerManager;
    }

    public static VehicleManager getVehicleManager() {
        return vehicleManager;
    }

    public static CarShowManager getCarShowManager() {
        return carShowManager;
    }

    public static CarShowOwnerManager getCarShowOwnerManager() {
        return carShowOwnerManager;
    }

    public static PersistManager getPersistManager() {
        return persistManager;
    }

    public javax.swing.JLabel getPasswordLabel() {
        return passwordLabel;
    }

    public javax.swing.JButton getSubmitButton() {
        return submitButton;
    }

    public javax.swing.JLabel getUserIDLabel() {
        return userIDLabel;
    }

    public javax.swing.JTextField getUserIDTextField() {
        return userIDTextField;
    }

    public javax.swing.JPasswordField getPasswordField() {
        return passwordField;
    }

    public Container getContainer() {
        return container;
    }

}
