/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.du.sirigaddepriyanka.view;

import edu.du.sirigaddepriyanka.controller.ownercontroller.OwnerUIController;
import edu.du.sirigaddepriyanka.model.business.manager.carshowmanager.CarShowManager;
import edu.du.sirigaddepriyanka.model.business.manager.carshowownermanager.CarShowOwnerManager;
import edu.du.sirigaddepriyanka.model.business.manager.ownermanager.OwnerManager;
import edu.du.sirigaddepriyanka.model.business.manager.vehiclemanager.VehicleManager;
import edu.du.sirigaddepriyanka.model.domain.Address;
import edu.du.sirigaddepriyanka.model.domain.Owner;
import java.awt.Container;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

/**
 *
 * @author priyankasirigadde
 */
public class OwnerUI extends javax.swing.JFrame {

    private OwnerManager ownerManager = null;
    private VehicleManager vehicleManager = null;
    private CarShowManager carShowManager = null;
    private CarShowOwnerManager carShowOwnerManager = null;
    private CarShowMainMenu carShowMainMenu = null;

    private final Container container = getContentPane();

    /**
     * Creates new form OwnerUI
     *
     * @param carShowMainMenu
     * @throws java.lang.Exception
     */
    public OwnerUI(CarShowMainMenu carShowMainMenu) throws Exception {

        initComponents();
        setTitle("Owner User Interface");

        this.carShowMainMenu = carShowMainMenu;
        ownerManager = carShowMainMenu.getOwnerManager();
        vehicleManager = CarShowMainMenu.getVehicleManager();
        carShowManager = CarShowMainMenu.getCarShowManager();
        carShowOwnerManager = CarShowMainMenu.getCarShowOwnerManager();

        ArrayList<Owner> ownerArrayList = ownerManager.getArrayList();

        ownerIDComboBox.removeAllItems();
        for (Owner owner : ownerArrayList) {
            ownerIDComboBox.addItem(owner.getOwnerID());
        }
        ownerIDComboBox.setSelectedIndex(0);
        ownerIDComboBox.setEditable(true);

        stateComboBox.removeAllItems();
        populateStateComboBox();
        stateComboBox.setSelectedItem("CO");

        OwnerUIController ownerUIController = new OwnerUIController(this);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent ev) {

            }
        });
        carShowMainMenu.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ownerIDTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        ownerIDLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        NoOfYearsLabel = new javax.swing.JLabel();
        NoOfYearsTextField = new javax.swing.JTextField();
        street1Label = new javax.swing.JLabel();
        street1TextField = new javax.swing.JTextField();
        street2Label = new javax.swing.JLabel();
        street2TextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        zipCodeLabel = new javax.swing.JLabel();
        zipCodeTextField = new javax.swing.JTextField();
        ownerFindButton = new javax.swing.JButton();
        ownerAddButton = new javax.swing.JButton();
        ownerRemoveButton = new javax.swing.JButton();
        ownerIDComboBox = new javax.swing.JComboBox<>();
        ownerInformationLabel = new javax.swing.JLabel();
        addressInformationLabel = new javax.swing.JLabel();
        stateComboBox = new javax.swing.JComboBox<>();
        ownerMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ownerIDLabel.setText("Owner ID");

        firstNameLabel.setText("First Name");

        firstNameTextField.setNextFocusableComponent(lastNameTextField);

        lastNameLabel.setText("LastName");

        lastNameTextField.setNextFocusableComponent(phoneNumberTextField);

        phoneNumberLabel.setText("Phone Number");

        phoneNumberTextField.setNextFocusableComponent(NoOfYearsTextField);

        NoOfYearsLabel.setText("No. of Years");

        street1Label.setText("Street 1");

        street2Label.setText("Street 2");

        cityLabel.setText("City");

        stateLabel.setText("State");

        zipCodeLabel.setText("Zip Code");

        ownerFindButton.setText("Find");

        ownerAddButton.setText("Add");

        ownerRemoveButton.setText("Remove");

        ownerIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ownerIDComboBox.setFocusCycleRoot(true);
        ownerIDComboBox.setNextFocusableComponent(firstNameTextField);

        ownerInformationLabel.setText("Owner Information");

        addressInformationLabel.setText("Address Information");

        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jMenu1.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Exit the System");
        jMenu1.add(exitMenuItem);

        ownerMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        ownerMenuBar.add(jMenu2);

        setJMenuBar(ownerMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ownerIDLabel)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(phoneNumberLabel)
                            .addComponent(NoOfYearsLabel))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ownerIDComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE)
                                .addComponent(NoOfYearsTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phoneNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ownerFindButton)
                                .addGap(59, 59, 59)
                                .addComponent(ownerAddButton)
                                .addGap(76, 76, 76)
                                .addComponent(ownerRemoveButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ownerInformationLabel)
                        .addGap(236, 236, 236)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(street1Label)
                            .addComponent(addressInformationLabel)
                            .addComponent(street2Label)
                            .addComponent(cityLabel)
                            .addComponent(stateLabel)
                            .addComponent(zipCodeLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(street1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(street2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(cityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(stateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerInformationLabel)
                    .addComponent(addressInformationLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ownerIDLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(street1Label)
                        .addComponent(street1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ownerIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(street2Label)
                    .addComponent(street2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastNameLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cityLabel)
                        .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel)
                    .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoOfYearsLabel)
                    .addComponent(NoOfYearsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCodeLabel)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerFindButton)
                    .addComponent(ownerAddButton)
                    .addComponent(ownerRemoveButton))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                // new OwnerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NoOfYearsLabel;
    private javax.swing.JTextField NoOfYearsTextField;
    private javax.swing.JLabel addressInformationLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton ownerAddButton;
    private javax.swing.JButton ownerFindButton;
    private javax.swing.JComboBox<String> ownerIDComboBox;
    private javax.swing.JLabel ownerIDLabel;
    private javax.swing.JTextField ownerIDTextField;
    private javax.swing.JLabel ownerInformationLabel;
    private javax.swing.JMenuBar ownerMenuBar;
    private javax.swing.JButton ownerRemoveButton;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JLabel street1Label;
    private javax.swing.JTextField street1TextField;
    private javax.swing.JLabel street2Label;
    private javax.swing.JTextField street2TextField;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables

    private void populateStateComboBox() {
        stateComboBox.addItem("AK");
        stateComboBox.addItem("AL");
        stateComboBox.addItem("AR");
        stateComboBox.addItem("AS");
        stateComboBox.addItem("AZ");
        stateComboBox.addItem("CA");
        stateComboBox.addItem("CO");
        stateComboBox.addItem("CT");
        stateComboBox.addItem("DC");
        stateComboBox.addItem("DE");
        stateComboBox.addItem("FL");
        stateComboBox.addItem("FM");
        stateComboBox.addItem("GA");
        stateComboBox.addItem("GU");
        stateComboBox.addItem("HI");
        stateComboBox.addItem("IA");
        stateComboBox.addItem("ID");
        stateComboBox.addItem("IL");
        stateComboBox.addItem("IN");
        stateComboBox.addItem("KS");
        stateComboBox.addItem("KY");
        stateComboBox.addItem("LA");
        stateComboBox.addItem("MA");
        stateComboBox.addItem("MD");
        stateComboBox.addItem("ME");
        stateComboBox.addItem("MH");
        stateComboBox.addItem("MI");
        stateComboBox.addItem("MN");
        stateComboBox.addItem("MO");
        stateComboBox.addItem("MP");
        stateComboBox.addItem("MS");
        stateComboBox.addItem("MT");
    }

    public OwnerManager getOwnerManager() {
        return ownerManager;
    }

    public VehicleManager getVehicleManager() {
        return vehicleManager;
    }

    public CarShowManager getCarShowManager() {
        return carShowManager;
    }

    public CarShowOwnerManager getCarShowOwnerManager() {
        return carShowOwnerManager;
    }

    public CarShowMainMenu getCarShowMainMenu() {
        return carShowMainMenu;
    }

    public Container getContainer() {
        return container;
    }

    public javax.swing.JLabel getNoOfYearsLabel() {
        return NoOfYearsLabel;
    }

    public javax.swing.JTextField getNoOfYearsTextField() {
        return NoOfYearsTextField;
    }

    public javax.swing.JLabel getAddressInformationLabel() {
        return addressInformationLabel;
    }

    public javax.swing.JLabel getCityLabel() {
        return cityLabel;
    }

    public javax.swing.JTextField getCityTextField() {
        return cityTextField;
    }

    public javax.swing.JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public javax.swing.JLabel getFirstNameLabel() {
        return firstNameLabel;
    }

    public javax.swing.JTextField getFirstNameTextField() {
        return firstNameTextField;
    }

    public javax.swing.JMenu getjMenu1() {
        return jMenu1;
    }

    public javax.swing.JMenu getjMenu2() {
        return jMenu2;
    }

    public javax.swing.JLabel getLastNameLabel() {
        return lastNameLabel;
    }

    public javax.swing.JTextField getLastNameTextField() {
        return lastNameTextField;
    }

    public javax.swing.JButton getOwnerAddButton() {
        return ownerAddButton;
    }

    public javax.swing.JButton getOwnerFindButton() {
        return ownerFindButton;
    }

    public javax.swing.JComboBox<String> getOwnerIDComboBox() {
        return ownerIDComboBox;
    }

    public javax.swing.JLabel getOwnerIDLabel() {
        return ownerIDLabel;
    }

    public javax.swing.JTextField getOwnerIDTextField() {
        return ownerIDTextField;
    }

    public javax.swing.JLabel getOwnerInformationLabel() {
        return ownerInformationLabel;
    }

    public javax.swing.JMenuBar getOwnerMenuBar() {
        return ownerMenuBar;
    }

    public javax.swing.JButton getOwnerRemoveButton() {
        return ownerRemoveButton;
    }

    public javax.swing.JLabel getPhoneNumberLabel() {
        return phoneNumberLabel;
    }

    public javax.swing.JTextField getPhoneNumberTextField() {
        return phoneNumberTextField;
    }

    public javax.swing.JComboBox<String> getStateComboBox() {
        return stateComboBox;
    }

    public javax.swing.JLabel getStateLabel() {
        return stateLabel;
    }

    public javax.swing.JTextField getStateTextField() {
        return stateTextField;
    }

    public javax.swing.JLabel getStreet1Label() {
        return street1Label;
    }

    public javax.swing.JTextField getStreet1TextField() {
        return street1TextField;
    }

    public javax.swing.JLabel getStreet2Label() {
        return street2Label;
    }

    public javax.swing.JTextField getStreet2TextField() {
        return street2TextField;
    }

    public javax.swing.JLabel getZipCodeLabel() {
        return zipCodeLabel;
    }

    public javax.swing.JTextField getZipCodeTextField() {
        return zipCodeTextField;
    }

    /*
    *displays the information
    */
    public void putOwnerInfo(Owner inOwner) {
        Owner owner = inOwner;
        Address address = owner.getAddress();

        ownerIDComboBox.setSelectedItem(owner.getOwnerID());
        firstNameTextField.setText(owner.getFirstName());
        lastNameTextField.setText(owner.getLastName());
        phoneNumberTextField.setText(owner.getPhoneNumber());
        NoOfYearsTextField.setText(Integer.toString(owner.getNumYears()));
        street1TextField.setText(address.getStreet1());
        street2TextField.setText(address.getStreet2());
        zipCodeTextField.setText(address.getZipcode());
        stateTextField.setText(address.getState());
        cityTextField.setText(address.getCity());
    }

    /*
    *retrieves the information
    */
    public Owner getOwnerInfo() {
        Owner owner = new Owner();
        Address address = new Address();

        owner.setOwnerID((String) ownerIDComboBox.getSelectedItem());
        owner.setFirstName(firstNameTextField.getText());
        owner.setLastName(lastNameTextField.getText());
        owner.setPhoneNumber(phoneNumberTextField.getText());
        owner.setNumYears(Integer.parseInt(NoOfYearsTextField.getText()));

        address.setStreet1(street1TextField.getText());
        address.setStreet2(street2TextField.getText());
        address.setCity(cityTextField.getText());
        address.setState((String) stateComboBox.getSelectedItem());
        address.setZipcode(zipCodeTextField.getText());

        owner.setAddress(address);

        return owner;
    }

    /*
    *clears the frame
    */
    public void clearOwnerInfo() {
        ownerIDComboBox.setSelectedItem(0);
        firstNameTextField.setText("");
        lastNameTextField.setText("");
        phoneNumberTextField.setText("");
        NoOfYearsTextField.setText("");
        street1TextField.setText("");
        street2TextField.setText("");
        zipCodeTextField.setText("");
        stateComboBox.setSelectedItem("CO");
        cityTextField.setText("");
    }
}
