/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.du.sirigaddepriyanka.view;

import edu.du.sirigaddepriyanka.controller.vehiclecontroller.VehicleUIController;
import edu.du.sirigaddepriyanka.model.business.manager.carshowmanager.CarShowManager;
import edu.du.sirigaddepriyanka.model.business.manager.carshowownermanager.CarShowOwnerManager;
import edu.du.sirigaddepriyanka.model.business.manager.ownermanager.OwnerManager;
import edu.du.sirigaddepriyanka.model.business.manager.vehiclemanager.VehicleManager;
import edu.du.sirigaddepriyanka.model.domain.Owner;
import edu.du.sirigaddepriyanka.model.domain.Vehicle;
import edu.du.sirigaddepriyanka.model.domain.VehicleClassification;
import java.awt.Container;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

/**
 *
 * @author priyankasirigadde
 */
public class VehicleUI extends javax.swing.JFrame {

    private OwnerManager ownerManager = null;
    private VehicleManager vehicleManager = null;
    private CarShowManager carShowManager = null;
    private CarShowOwnerManager carShowOwnerManager = null;
    private CarShowMainMenu carShowMainMenu = null;

    private final Container container = getContentPane();

    /**
     * Creates new form VehicleUI
     * @param carShowMainMenu
     * @throws java.lang.Exception
     */
    public VehicleUI(CarShowMainMenu carShowMainMenu) throws Exception {

        setTitle("Vehicle User Interface");
        initComponents();

        this.carShowMainMenu = carShowMainMenu;
        ownerManager = carShowMainMenu.getOwnerManager();
        vehicleManager = carShowMainMenu.getVehicleManager();
        carShowManager = carShowMainMenu.getCarShowManager();
        carShowOwnerManager = carShowMainMenu.getCarShowOwnerManager();

        ArrayList<Vehicle> vehicleArrayList = vehicleManager.getArrayList();
        ArrayList<Owner> ownerArrayList = ownerManager.getArrayList();

        vehicleIDComboBox.removeAllItems();
        for (Vehicle vehicle : vehicleArrayList) {
            vehicleIDComboBox.addItem(vehicle.getVehicleID());
        }
        vehicleIDComboBox.setSelectedIndex(0);
        vehicleIDComboBox.setEditable(true);

        ownerIDComboBox.removeAllItems();
        for (Owner owner : ownerArrayList) {
            ownerIDComboBox.addItem(owner.getOwnerID());
        }
        ownerIDComboBox.setSelectedIndex(0);

        VehicleUIController vehicleUIController = new VehicleUIController(this);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent ev) {

            }
        });
        carShowMainMenu.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehicleIDLabel = new javax.swing.JLabel();
        ownerIDLabel = new javax.swing.JLabel();
        manufacturerLabel = new javax.swing.JLabel();
        manufacturerTextField = new javax.swing.JTextField();
        modelYearLabel = new javax.swing.JLabel();
        modelYearTextField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        subModelLabel = new javax.swing.JLabel();
        subModelTextField = new javax.swing.JTextField();
        isVehicleInsuredRadioButton = new javax.swing.JRadioButton();
        vehicleClassificationComboBox = new javax.swing.JComboBox<>();
        vehicleFindButton = new javax.swing.JButton();
        vehicleAddButton = new javax.swing.JButton();
        vehicleRemoveButton = new javax.swing.JButton();
        vehicleClassificationLabel = new javax.swing.JLabel();
        ownerIDComboBox = new javax.swing.JComboBox<>();
        vehicleIDComboBox = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vehicleIDLabel.setText("Vehicle ID");

        ownerIDLabel.setText("Owner ID");

        manufacturerLabel.setText("Manufacturer");

        modelYearLabel.setText("Model Year");

        modelLabel.setText("Model");

        subModelLabel.setText("Sub Model");

        isVehicleInsuredRadioButton.setText("is Vehicle Insured");

        vehicleClassificationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ANTIQUE", "CLASSIC", "MODERN" }));

        vehicleFindButton.setText("Find");

        vehicleAddButton.setText("Add");

        vehicleRemoveButton.setText("Remove");

        vehicleClassificationLabel.setText("Vehicle Classification");

        ownerIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        vehicleIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jMenu1.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Exit the System");
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(vehicleFindButton)
                        .addGap(51, 51, 51)
                        .addComponent(vehicleAddButton)
                        .addGap(52, 52, 52)
                        .addComponent(vehicleRemoveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(isVehicleInsuredRadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehicleIDLabel)
                                    .addComponent(ownerIDLabel)
                                    .addComponent(manufacturerLabel)
                                    .addComponent(modelYearLabel)
                                    .addComponent(modelLabel)
                                    .addComponent(subModelLabel)
                                    .addComponent(vehicleClassificationLabel))))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vehicleClassificationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(manufacturerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(modelYearTextField)
                                .addComponent(modelTextField)
                                .addComponent(subModelTextField))
                            .addComponent(ownerIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vehicleIDLabel)
                    .addComponent(vehicleIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ownerIDLabel)
                    .addComponent(ownerIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturerLabel)
                    .addComponent(manufacturerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelYearLabel)
                    .addComponent(modelYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLabel)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subModelLabel)
                    .addComponent(subModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleClassificationLabel)
                    .addComponent(vehicleClassificationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isVehicleInsuredRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleFindButton)
                    .addComponent(vehicleAddButton)
                    .addComponent(vehicleRemoveButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new VehicleUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JRadioButton isVehicleInsuredRadioButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel manufacturerLabel;
    private javax.swing.JTextField manufacturerTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JLabel modelYearLabel;
    private javax.swing.JTextField modelYearTextField;
    private javax.swing.JComboBox<String> ownerIDComboBox;
    private javax.swing.JLabel ownerIDLabel;
    private javax.swing.JLabel subModelLabel;
    private javax.swing.JTextField subModelTextField;
    private javax.swing.JButton vehicleAddButton;
    private javax.swing.JComboBox<String> vehicleClassificationComboBox;
    private javax.swing.JLabel vehicleClassificationLabel;
    private javax.swing.JButton vehicleFindButton;
    private javax.swing.JComboBox<String> vehicleIDComboBox;
    private javax.swing.JLabel vehicleIDLabel;
    private javax.swing.JButton vehicleRemoveButton;
    // End of variables declaration//GEN-END:variables

    public OwnerManager getOwnerManager() {
        return ownerManager;
    }

    public VehicleManager getVehicleManager() {
        return vehicleManager;
    }

    public CarShowManager getCarShowManager() {
        return carShowManager;
    }

    public CarShowOwnerManager getCarShowOwnerManager() {
        return carShowOwnerManager;
    }

    public CarShowMainMenu getCarShowMainMenu() {
        return carShowMainMenu;
    }

    public Container getContainer() {
        return container;
    }

    public javax.swing.JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public javax.swing.JRadioButton getIsVehicleInsuredRadioButton() {
        return isVehicleInsuredRadioButton;
    }

    public javax.swing.JMenu getjMenu1() {
        return jMenu1;
    }

    public javax.swing.JMenu getjMenu2() {
        return jMenu2;
    }

    public javax.swing.JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public javax.swing.JLabel getManufacturerLabel() {
        return manufacturerLabel;
    }

    public javax.swing.JTextField getManufacturerTextField() {
        return manufacturerTextField;
    }

    public javax.swing.JLabel getModelLabel() {
        return modelLabel;
    }

    public javax.swing.JTextField getModelTextField() {
        return modelTextField;
    }

    public javax.swing.JLabel getModelYearLabel() {
        return modelYearLabel;
    }

    public javax.swing.JTextField getModelYearTextField() {
        return modelYearTextField;
    }

    public javax.swing.JComboBox<String> getOwnerIDComboBox() {
        return ownerIDComboBox;
    }

    public javax.swing.JLabel getOwnerIDLabel() {
        return ownerIDLabel;
    }

    public javax.swing.JLabel getSubModelLabel() {
        return subModelLabel;
    }

    public javax.swing.JTextField getSubModelTextField() {
        return subModelTextField;
    }

    public javax.swing.JButton getVehicleAddButton() {
        return vehicleAddButton;
    }

    public javax.swing.JComboBox<String> getVehicleClassificationComboBox() {
        return vehicleClassificationComboBox;
    }

    public javax.swing.JLabel getVehicleClassificationLabel() {
        return vehicleClassificationLabel;
    }

    public javax.swing.JButton getVehicleFindButton() {
        return vehicleFindButton;
    }

    public javax.swing.JComboBox<String> getVehicleIDComboBox() {
        return vehicleIDComboBox;
    }

    public javax.swing.JLabel getVehicleIDLabel() {
        return vehicleIDLabel;
    }

    public javax.swing.JButton getVehicleRemoveButton() {
        return vehicleRemoveButton;
    }

    /*
    *displays the information
    */
    public void putVehicleInfo(Vehicle inVehicle) {
        Vehicle vehicle = inVehicle;

        vehicleIDComboBox.setSelectedItem(vehicle.getVehicleID());
        ownerIDComboBox.setSelectedItem(vehicle.getOwnerID());
        manufacturerTextField.setText(vehicle.getManufacturer());
        modelTextField.setText(vehicle.getModel());
        subModelTextField.setText(vehicle.getSubModel());
        modelYearTextField.setText(Integer.toString(vehicle.getModelYear()));
        vehicleClassificationComboBox.setSelectedItem(vehicle.getVehicleClassification().toString());
        isVehicleInsuredRadioButton.setSelected(vehicle.isIsInsured());
    }

    /*
    *retrieves the information
    */
    public Vehicle getVehicleInfo() {
        Vehicle vehicle = new Vehicle();

        vehicle.setVehicleID((String) vehicleIDComboBox.getSelectedItem());
        vehicle.setOwnerID((String) ownerIDComboBox.getSelectedItem());
        vehicle.setManufacturer(manufacturerTextField.getText());
        vehicle.setModel(modelTextField.getText());
        vehicle.setSubModel(subModelTextField.getText());
        vehicle.setModelYear(Integer.parseInt(modelYearTextField.getText()));
        vehicle.setVehicleClassification(VehicleClassification.valueOf((String) vehicleClassificationComboBox.getSelectedItem()));
        vehicle.setIsInsured(isVehicleInsuredRadioButton.isSelected());
        return vehicle;
    }

    /*
    *clears the frame
    */
    public void clearVehicleInfo() {
        vehicleIDComboBox.setSelectedItem(0);
        ownerIDComboBox.setSelectedItem(0);
        manufacturerTextField.setText("");
        modelTextField.setText("");
        subModelTextField.setText("");
        modelYearTextField.setText("");
        vehicleClassificationComboBox.setSelectedItem(0);
        isVehicleInsuredRadioButton.setSelected(false);
    }
}
